AudioPolicyManager: Fix compilation error on 8.0.0_r23
 * This updates selectedDeviceId type (required after https://github.com/LineageOS/android_frameworks_av/commit/2ac7694396640821f6723672e25b2372220bf060)
   in order to fix the following error:

     cannot initialize a parameter of type 'audio_port_handle_t *' (aka 'int *') with an rvalue of type 'audio_port_handle_t' (aka 'int')

Change-Id: Ic94e4de38bb4c592fddc94954665053dcf505d36